kind: Service
apiVersion: v1
metadata:
  name: vm-metrics
  namespace: demo-vm
  labels:
    servicetype: metrics
spec:
  ports:
    - name: metrics
      protocol: TCP
      port: 44322
      targetPort: 44322
  selector:
    vm.kubevirt.io/name: rhel9-vm
